### PR TITLE
Fix pylint issues

### PR DESCRIPTION
**Pull request by jkonecny12**
Pylint has a set of new issues raised with the new version. Let's fix these.

### CODE REVIEW

**Comment by jkonecny12** [comment]
I don't understand it but locally I don't see these pylint errors even in the newest Rawhide container...

Have to find that out.

**Comment by poncovka** [comment]
> I don't understand it but locally I don't see these pylint errors even in the newest Rawhide container...
> 
> Have to find that out.

Don't you need `--pull-always` or something like that?

**Comment by jkonecny12** [comment]
I would expect that the machines here don't have the image. I'll check that.

**Comment by poncovka** [comment]
> I would expect that the machines here don't have the image. I'll check that.

It would be for the local testing.

**Comment by jkonecny12** [comment]
> > I would expect that the machines here don't have the image. I'll check that.
> 
> It would be for the local testing.

It's not that. I done a pull manually.

**Comment by jkonecny12** [comment]
Do have a better idea for fixing this? Maybe I'm just blind but I don't see the cyclic imports they are complaining about and especially not from the given file. I can't just disable this test on the given file for some reason...

**Comment by VladimirSlavik** [comment]
Not sure if this helps, but, on a f35 host...
- If I run the container via makefile target, it's ok.
- If I run the container manually piece by piece, it's ok.
- If I run the make targets directly on the host, it's ok.

```
pylint-2.15.3
astroid-2.12.10
dill-0.3.5.1
```

**Comment by poncovka** [comment]
> Do have a better idea for fixing this? Maybe I'm just blind but I don't see the cyclic imports they are complaining about and especially not from the given file. I can't just disable this test on the given file for some reason...

These are refactorization warnings, so I would say it is fine.

**Comment by jkonecny12** [comment]
Thanks for confirmation. Merging.

**Pull request merged**
