### PR TITLE
Migrate to SPDX license

### PR DESCRIPTION
**Pull request by jkonecny12**
Detailed description is here:
https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Thanks!

**Comment by jkonecny12** [comment]
Failed job should be fixed by https://github.com/rhinstaller/python-simpleline/pull/128

**Comment by jkonecny12** [comment]
Downstream build: https://koji.fedoraproject.org/koji/taskinfo?taskID=95537442

**Review by VladimirSlavik — APPROVED** [review]

**Pull request merged**
