### PR TITLE
Migrate COPR daily COPR builds to Packit

### PR DESCRIPTION
**Pull request by jkonecny12**

### CODE REVIEW

**Comment by jkonecny12** [comment]
Tested here: https://github.com/jkonecny12/python-simpleline/commit/b7659dfde8c5b11753cfcaf4d207a1aab1a9afdf

**Review by martinpitt — APPROVED** [review]
Cheers!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

The PR has COPR twice in its name, but that's not exactly important :)

**Comment by jkonecny12** [comment]
**UPDATED:**
* Based on this [Test](https://github.com/jkonecny12/python-simpleline/commit/a76d9ac8c70afb0c17ff1eb95931b4336ea5b305) we don't need to add this COPR repository for non-Anaconda builds.

**Pull request merged**
